package nzuzi.joao.criacao_consulta_numero_bi.util;

import nzuzi.joao.criacao_consulta_numero_bi.enumerate.Comunas;
import nzuzi.joao.criacao_consulta_numero_bi.enumerate.Municipios;
import nzuzi.joao.criacao_consulta_numero_bi.model.Comuna;
import nzuzi.joao.criacao_consulta_numero_bi.model.Municipio;
import nzuzi.joao.criacao_consulta_numero_bi.model.Provincia;

import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.stream.Collectors;
import static nzuzi.joao.criacao_consulta_numero_bi.enumerate.Provincias.*;

public class ListaCodigos {

    public static Collection<Provincia> verificarCodigoProvincia(String codigo) {

        Collection<Provincia> items = new ArrayList<>();

        items.add(new Provincia(BENGUELA.getCode(), BENGUELA.getDescription()));
        items.add(new Provincia(BIE.getCode(), BIE.getDescription()));
        items.add(new Provincia(BENGO.getCode(), BENGO.getDescription()));
        items.add(new Provincia(CABINDA.getCode(), CABINDA.getDescription()));
        items.add(new Provincia(CUANDO_CUBANGO.getCode(), CUANDO_CUBANGO.getDescription()));
        items.add(new Provincia(CUNENE.getCode(), CUNENE.getDescription()));
        items.add(new Provincia(CUANZA_NORTE.getCode(), CUANZA_NORTE.getDescription()));
        items.add(new Provincia(CUANZA_SUL.getCode(), CUANZA_SUL.getDescription()));
        items.add(new Provincia(HUILA.getCode(), HUILA.getDescription()));
        items.add(new Provincia(HUAMBO.getCode(), HUAMBO.getDescription()));
        items.add(new Provincia(LUANDA.getCode(), LUANDA.getDescription()));
        items.add(new Provincia(LUNDA_NORTE.getCode(), LUNDA_NORTE.getDescription()));
        items.add(new Provincia(LUNDA_SUL.getCode(), LUNDA_SUL.getDescription()));
        items.add(new Provincia(MALANJE.getCode(), MALANJE.getDescription()));
        items.add(new Provincia(MOXICO.getCode(), MOXICO.getDescription()));
        items.add(new Provincia(NAMIBE.getCode(), NAMIBE.getDescription()));
        items.add(new Provincia(UIGE.getCode(), UIGE.getDescription()));
        items.add(new Provincia(ZAIRE.getCode(), ZAIRE.getDescription()));

        return items.stream().filter(i -> i.getCodigo().equalsIgnoreCase(codigo)).collect(Collectors.toList());
    }

    public static Collection<Municipio> verificarCodigoMunicipio(String codigo) {

        Collection<Municipio> items = new ArrayList<>();

        items.add(new Municipio(BENGUELA.getCode(), Municipios.BAIA_FARTA.getDescription()));
        items.add(new Municipio(BENGUELA.getCode(), Municipios.BALOMBO.getDescription()));
        items.add(new Municipio(BENGUELA.getCode(), Municipios.BENGUELA.getDescription()));
        items.add(new Municipio(BENGUELA.getCode(), Municipios.BOCOIO.getDescription()));
        items.add(new Municipio(BENGUELA.getCode(), Municipios.CAIMBAMBO.getDescription()));
        items.add(new Municipio(BENGUELA.getCode(), Municipios.CATUMBELA.getDescription()));
        items.add(new Municipio(BENGUELA.getCode(), Municipios.CHONGOROI.getDescription()));
        items.add(new Municipio(BENGUELA.getCode(), Municipios.CUBAL.getDescription()));
        items.add(new Municipio(BENGUELA.getCode(), Municipios.GANDA.getDescription()));
        items.add(new Municipio(BENGUELA.getCode(), Municipios.LOBITO.getDescription()));
        items.add(new Municipio(BIE.getCode(), Municipios.ANDULO.getDescription()));
        items.add(new Municipio(BIE.getCode(), Municipios.CAMACUPA.getDescription()));
        items.add(new Municipio(BIE.getCode(), Municipios.CATABOLA.getDescription()));
        items.add(new Municipio(BIE.getCode(), Municipios.CHINGUAR.getDescription()));
        items.add(new Municipio(BIE.getCode(), Municipios.CHITEMBO.getDescription()));
        items.add(new Municipio(BIE.getCode(), Municipios.CUEMBA.getDescription()));
        items.add(new Municipio(BIE.getCode(), Municipios.CUITO.getDescription()));
        items.add(new Municipio(BIE.getCode(), Municipios.CUNHINGA.getDescription()));
        items.add(new Municipio(BIE.getCode(), Municipios.NHAREA.getDescription()));
        items.add(new Municipio(BENGO.getCode(), Municipios.AMBRIZ.getDescription()));
        items.add(new Municipio(BENGO.getCode(), Municipios.BULA_ATUMBA.getDescription()));
        items.add(new Municipio(BENGO.getCode(), Municipios.DANDE.getDescription()));
        items.add(new Municipio(BENGO.getCode(), Municipios.DEMBOS.getDescription()));
        items.add(new Municipio(BENGO.getCode(), Municipios.NAMBUANGONGO.getDescription()));
        items.add(new Municipio(BENGO.getCode(), Municipios.PANGO_ALUQUEM.getDescription()));
        items.add(new Municipio(BENGO.getCode(), Municipios.PANGOALUQUEM.getDescription()));
        items.add(new Municipio(CABINDA.getCode(), Municipios.BELIZE.getDescription()));
        items.add(new Municipio(CABINDA.getCode(), Municipios.BUCO_ZAU.getDescription()));
        items.add(new Municipio(CABINDA.getCode(), Municipios.CABINDA.getDescription()));
        items.add(new Municipio(CABINDA.getCode(), Municipios.CACONGO.getDescription()));
        items.add(new Municipio(CUANDO_CUBANGO.getCode(), Municipios.CALAI.getDescription()));
        items.add(new Municipio(CUANDO_CUBANGO.getCode(), Municipios.CUANGAR.getDescription()));
        items.add(new Municipio(CUANDO_CUBANGO.getCode(), Municipios.CUCHI.getDescription()));
        items.add(new Municipio(CUANDO_CUBANGO.getCode(), Municipios.CUITO_CUANAVALE.getDescription()));
        items.add(new Municipio(CUANDO_CUBANGO.getCode(), Municipios.DIRICO.getDescription()));
        items.add(new Municipio(CUANDO_CUBANGO.getCode(), Municipios.MAVINGA.getDescription()));
        items.add(new Municipio(CUANDO_CUBANGO.getCode(), Municipios.MENONGUE.getDescription()));
        items.add(new Municipio(CUANDO_CUBANGO.getCode(), Municipios.NANCOVA.getDescription()));
        items.add(new Municipio(CUANDO_CUBANGO.getCode(), Municipios.RIVUNGO.getDescription()));
        items.add(new Municipio(CUNENE.getCode(), Municipios.CAHAMA.getDescription()));
        items.add(new Municipio(CUNENE.getCode(), Municipios.CUANHAMA.getDescription()));
        items.add(new Municipio(CUNENE.getCode(), Municipios.CUROCA.getDescription()));
        items.add(new Municipio(CUNENE.getCode(), Municipios.CUVELAI.getDescription()));
        items.add(new Municipio(CUNENE.getCode(), Municipios.NAMACUNDE.getDescription()));
        items.add(new Municipio(CUNENE.getCode(), Municipios.OMBANDJA.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.BANGA.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.BOLONGONGO.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.AMBACA.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.CAMBAMBE.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.CAZENGO.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.GOLUNGO_ALTO.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.LUCALA.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.LUCAPA.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.NGONGUEMBO.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.QUICULUNGO.getDescription()));
        items.add(new Municipio(CUANZA_NORTE.getCode(), Municipios.SAMBA_CAJU.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.AMBOIM.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.CASSONGUE.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.CELA.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.CONDA.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.EBO.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.LIBOLO.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.MUSSENDE.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.PORTO_AMBOIM.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.QUIBALA.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.QUILENDA.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.SELES.getDescription()));
        items.add(new Municipio(CUANZA_SUL.getCode(), Municipios.SUMBE.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.CACONDA.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.CACULA.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.CALUQUEMBE.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.CHIBIA.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.CHICOMBA.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.CHIPINDO.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.CUVANGO.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.GAMBOS.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.HUMPATA.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.JAMBA.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.LUBANGO.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.MATALA.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.QUILENGUES.getDescription()));
        items.add(new Municipio(HUILA.getCode(), Municipios.QUIPUNGO.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.BAILUNDO.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.CAALA.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.CACHIUNGO.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.CHICALA_CHOLOANGA.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.CHINJENJE.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.ECUNHA.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.HUAMBO.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.LONDUIMBALI.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.LONGONJO.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.MUNGO.getDescription()));
        items.add(new Municipio(HUAMBO.getCode(), Municipios.UCUMA.getDescription()));
        items.add(new Municipio(LUANDA.getCode(), Municipios.BELAS.getDescription()));
        items.add(new Municipio(LUANDA.getCode(), Municipios.CACUACO.getDescription()));
        items.add(new Municipio(LUANDA.getCode(), Municipios.CAZENGA.getDescription()));
        items.add(new Municipio(LUANDA.getCode(), Municipios.ICOLO_BENGO.getDescription()));
        items.add(new Municipio(LUANDA.getCode(), Municipios.KILAMBA_KIAXI.getDescription()));
        items.add(new Municipio(LUANDA.getCode(), Municipios.LUANDA.getDescription()));
        items.add(new Municipio(LUANDA.getCode(), Municipios.QUICAMA.getDescription()));
        items.add(new Municipio(LUANDA.getCode(), Municipios.TALATONA.getDescription()));
        items.add(new Municipio(LUANDA.getCode(), Municipios.VIANA.getDescription()));
        items.add(new Municipio(LUNDA_NORTE.getCode(), Municipios.CAMBULO.getDescription()));
        items.add(new Municipio(LUNDA_NORTE.getCode(), Municipios.CAPENDA_CAMULEMBA.getDescription()));
        items.add(new Municipio(LUNDA_NORTE.getCode(), Municipios.CAUNGULA.getDescription()));
        items.add(new Municipio(LUNDA_NORTE.getCode(), Municipios.CHITATO.getDescription()));
        items.add(new Municipio(LUNDA_NORTE.getCode(), Municipios.CUANGO.getDescription()));
        items.add(new Municipio(LUNDA_NORTE.getCode(), Municipios.CUILO.getDescription()));
        items.add(new Municipio(LUNDA_NORTE.getCode(), Municipios.LOVUA.getDescription()));
        items.add(new Municipio(LUNDA_NORTE.getCode(), Municipios.LUBALO.getDescription()));
        items.add(new Municipio(LUNDA_NORTE.getCode(), Municipios.XA_MUTEBA.getDescription()));
        items.add(new Municipio(LUNDA_SUL.getCode(), Municipios.CACOLO.getDescription()));
        items.add(new Municipio(LUNDA_SUL.getCode(), Municipios.DALA.getDescription()));
        items.add(new Municipio(LUNDA_SUL.getCode(), Municipios.MUCONDA.getDescription()));
        items.add(new Municipio(LUNDA_SUL.getCode(), Municipios.SAURIMO.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.CACUSO.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.CAHOMBO.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.CALANDULA.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.CAMBUNDI_CATEMBO.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.CANGANDALA.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.KIWABA_NZOJI.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.KUNDA_DYA_BAZE.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.LUQUEMBO.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.MALANJE.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.MARIMBA.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.MASSANGO.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.MUCARI.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.QUELA.getDescription()));
        items.add(new Municipio(MALANJE.getCode(), Municipios.QUIRIMA.getDescription()));
        items.add(new Municipio(MOXICO.getCode(), Municipios.ALTO_ZAMBEZE.getDescription()));
        items.add(new Municipio(MOXICO.getCode(), Municipios.BUNDAS.getDescription()));
        items.add(new Municipio(MOXICO.getCode(), Municipios.CAMANONGUE.getDescription()));
        items.add(new Municipio(MOXICO.getCode(), Municipios.CAMEIA.getDescription()));
        items.add(new Municipio(MOXICO.getCode(), Municipios.LEUA.getDescription()));
        items.add(new Municipio(MOXICO.getCode(), Municipios.LUACANO.getDescription()));
        items.add(new Municipio(MOXICO.getCode(), Municipios.LUAU.getDescription()));
        items.add(new Municipio(MOXICO.getCode(), Municipios.LUCHAZES.getDescription()));
        items.add(new Municipio(MOXICO.getCode(), Municipios.MOXICO.getDescription()));
        items.add(new Municipio(NAMIBE.getCode(), Municipios.BIBALA.getDescription()));
        items.add(new Municipio(NAMIBE.getCode(), Municipios.CAMUCUIO.getDescription()));
        items.add(new Municipio(NAMIBE.getCode(), Municipios.MOCAMEDES.getDescription()));
        items.add(new Municipio(NAMIBE.getCode(), Municipios.TOMBWA.getDescription()));
        items.add(new Municipio(NAMIBE.getCode(), Municipios.VIREI.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.ALTO_CAUALE.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.AMBUILA.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.BEMBE.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.BUENGAS.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.BUNGO.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.DAMBA.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.DANGE_QUITEXE.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.MAQUELA_DO_ZOMBO.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.MILUNGA.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.MUCABA.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.NEGAGE.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.POMBO.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.PURI.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.QUIMBELE.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.SONGO.getDescription()));
        items.add(new Municipio(UIGE.getCode(), Municipios.UIGE.getDescription()));
        items.add(new Municipio(ZAIRE.getCode(), Municipios.CUIMBA.getDescription()));
        items.add(new Municipio(ZAIRE.getCode(), Municipios.MBANZA_KONGO.getDescription()));
        items.add(new Municipio(ZAIRE.getCode(), Municipios.NOQUI.getDescription()));
        items.add(new Municipio(ZAIRE.getCode(), Municipios.NZETO.getDescription()));
        items.add(new Municipio(ZAIRE.getCode(), Municipios.SOYO.getDescription()));
        items.add(new Municipio(ZAIRE.getCode(), Municipios.TOMBOCO.getDescription()));

        return items.stream().filter(i -> i.getCodigoMunicipio().equalsIgnoreCase(codigo)).collect(Collectors.toList());
    }

    public static Collection<Comuna> verificarCodigoComunaDistritoUrbano(String codigo) {

        return Comunas().stream().filter(i -> i.getCodigo().equalsIgnoreCase(codigo)).collect(Collectors.toList());

    }

    private static Collection<Comuna> Comunas(){
        Collection<Comuna> items = new ArrayList<>();

        items.add(new Comuna(BENGUELA.getCode(), Municipios.BAIA_FARTA.getDescription(), Comunas.BAIA_FARTA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BAIA_FARTA.getDescription(), Comunas.CALOHANGA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BAIA_FARTA.getDescription(), Comunas.DOMBEGRANDE.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BAIA_FARTA.getDescription(), Comunas.EQUIMINA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BALOMBO.getDescription(), Comunas.BALOMBO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BALOMBO.getDescription(), Comunas.CHINDUMBO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BALOMBO.getDescription(), Comunas.CHINGONGO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BALOMBO.getDescription(), Comunas.MACAMOMBOLO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BENGUELA.getDescription(), Comunas.BENGUELA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BOCOIO.getDescription(), Comunas.BOCOIO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BOCOIO.getDescription(), Comunas.CHILA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BOCOIO.getDescription(), Comunas.CUBAL_DO_LUMBO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BOCOIO.getDescription(), Comunas.MONTE_BELO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.BOCOIO.getDescription(), Comunas.PASSE.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CAIMBAMBO.getDescription(), Comunas.CAIAVE.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CAIMBAMBO.getDescription(), Comunas.CAIMBAMBO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CAIMBAMBO.getDescription(), Comunas.CANHAMELA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CAIMBAMBO.getDescription(), Comunas.CATENGUE.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CAIMBAMBO.getDescription(), Comunas.VIANGOMBE.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CATUMBELA.getDescription(), Comunas.BIOPIO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CATUMBELA.getDescription(), Comunas.CATUMBELA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CATUMBELA.getDescription(), Comunas.GAMA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CATUMBELA.getDescription(), Comunas.PRAIA_BEBE.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CHONGOROI.getDescription(), Comunas.BOLONGUERA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CHONGOROI.getDescription(), Comunas.CAMUINE.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CHONGOROI.getDescription(), Comunas.CHONGOROI.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CUBAL.getDescription(), Comunas.CAPUPA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CUBAL.getDescription(), Comunas.CUBAL.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CUBAL.getDescription(), Comunas.IAMBALA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.CUBAL.getDescription(), Comunas.TUMBULO.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.GANDA.getDescription(), Comunas.BABAERA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.GANDA.getDescription(), Comunas.CASSEQUE.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.GANDA.getDescription(), Comunas.CHICUMA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.GANDA.getDescription(), Comunas.EBANGA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.GANDA.getDescription(), Comunas.GANDA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.LOBITO.getDescription(), Comunas.CANATA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.LOBITO.getDescription(), Comunas.CANJALA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.LOBITO.getDescription(), Comunas.EGIPTO_PRAIA.getDescription()));
        items.add(new Comuna(BENGUELA.getCode(), Municipios.LOBITO.getDescription(), Comunas.LOBITO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.ANDULO.getDescription(), Comunas.ANDULO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.ANDULO.getDescription(), Comunas.CALUCINGA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.ANDULO.getDescription(), Comunas.CASSUMBE.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.ANDULO.getDescription(), Comunas.CHIVAULO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CAMACUPA.getDescription(), Comunas.CAMACUPA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CAMACUPA.getDescription(), Comunas.CUANZA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CAMACUPA.getDescription(), Comunas.MUINHA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CAMACUPA.getDescription(), Comunas.RINGOMA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CAMACUPA.getDescription(), Comunas.UMPULO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CATABOLA.getDescription(), Comunas.CAIUERA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CATABOLA.getDescription(), Comunas.CATABOLA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CATABOLA.getDescription(), Comunas.CHIPETA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CATABOLA.getDescription(), Comunas.CHIUCA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CATABOLA.getDescription(), Comunas.SANDE.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CHINGUAR.getDescription(), Comunas.CANGOTE.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CHINGUAR.getDescription(), Comunas.CHINGUAR.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CHINGUAR.getDescription(), Comunas.CUTATO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CHITEMBO.getDescription(), Comunas.CACHINGUES.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CHITEMBO.getDescription(), Comunas.CHITEMBO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CHITEMBO.getDescription(), Comunas.MALENGUE.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CHITEMBO.getDescription(), Comunas.MUMBUE.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CHITEMBO.getDescription(), Comunas.MUTUMBO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CHITEMBO.getDescription(), Comunas.SOMA_CUANZA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUEMBA.getDescription(), Comunas.CUEMBA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUEMBA.getDescription(), Comunas.LUANDO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUEMBA.getDescription(), Comunas.MUNHANGO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUEMBA.getDescription(), Comunas.SACHINEMUNA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUITO.getDescription(), Comunas.CAMBANDUA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUITO.getDescription(), Comunas.CHICALA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUITO.getDescription(), Comunas.CUITO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUITO.getDescription(), Comunas.CUNJE.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUITO.getDescription(), Comunas.TRUMBA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUNHINGA.getDescription(), Comunas.BELO_HORIZONTE.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.CUNHINGA.getDescription(), Comunas.CUNHINGA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.NHAREA.getDescription(), Comunas.CAIEI.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.NHAREA.getDescription(), Comunas.DANDO.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.NHAREA.getDescription(), Comunas.GAMBA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.NHAREA.getDescription(), Comunas.LUBIA.getDescription()));
        items.add(new Comuna(BIE.getCode(), Municipios.NHAREA.getDescription(), Comunas.NHAREA.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.AMBRIZ.getDescription(), Comunas.AMBRIZ.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.AMBRIZ.getDescription(), Comunas.BELA_VISTA.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.AMBRIZ.getDescription(), Comunas.TABI.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.BULA_ATUMBA.getDescription(), Comunas.BULA_ATUMBA.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.BULA_ATUMBA.getDescription(), Comunas.QUIAGE.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.DANDE.getDescription(), Comunas.BARRA_DO_DANDE.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.DANDE.getDescription(), Comunas.CAXITO.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.DANDE.getDescription(), Comunas.MABUBAS.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.DANDE.getDescription(), Comunas.QUICABO.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.DANDE.getDescription(), Comunas.UCUA.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.DEMBOS.getDescription(), Comunas.COXE.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.DEMBOS.getDescription(), Comunas.PAREDES.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.DEMBOS.getDescription(), Comunas.PIRI.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.DEMBOS.getDescription(), Comunas.QUIBAXE.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.NAMBUANGONGO.getDescription(), Comunas.CAGE.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.NAMBUANGONGO.getDescription(), Comunas.CANACASSALA.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.NAMBUANGONGO.getDescription(), Comunas.GOMBE.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.NAMBUANGONGO.getDescription(), Comunas.MUXALUANDO.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.NAMBUANGONGO.getDescription(), Comunas.QUICUNZO.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.NAMBUANGONGO.getDescription(), Comunas.QUIXICO.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.NAMBUANGONGO.getDescription(), Comunas.ZALA.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.PANGO_ALUQUEM.getDescription(), Comunas.CAZUANGONGO.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.PANGOALUQUEM.getDescription(), Comunas.CAZUANGONGO.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.PANGO_ALUQUEM.getDescription(), Comunas.PANGO_ALUQUEM.getDescription()));
        items.add(new Comuna(BENGO.getCode(), Municipios.PANGOALUQUEM.getDescription(), Comunas.PANGOALUQUEM.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.BELIZE.getDescription(), Comunas.BELIZE.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.BELIZE.getDescription(), Comunas.LUALI.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.BELIZE.getDescription(), Comunas.MICONJE.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.BUCO_ZAU.getDescription(), Comunas.BUCOZAU.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.BUCO_ZAU.getDescription(), Comunas.INHUCA.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.BUCO_ZAU.getDescription(), Comunas.NECUTO.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.CABINDA.getDescription(), Comunas.CABINDA.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.CABINDA.getDescription(), Comunas.MALEMBO.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.CABINDA.getDescription(), Comunas.TANDO_ZINZE.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.CACONGO.getDescription(), Comunas.DINGE.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.CACONGO.getDescription(), Comunas.CACONGO.getDescription()));
        items.add(new Comuna(CABINDA.getCode(), Municipios.CACONGO.getDescription(), Comunas.MASSABI.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CALAI.getDescription(), Comunas.CALAI.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CALAI.getDescription(), Comunas.MAUE.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CALAI.getDescription(), Comunas.MAVENGUE.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUANGAR.getDescription(), Comunas.CAILA.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUANGAR.getDescription(), Comunas.CUANGAR.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUANGAR.getDescription(), Comunas.SAVATE.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUCHI.getDescription(), Comunas.CHINGUANJA.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUCHI.getDescription(), Comunas.CUCHI.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUCHI.getDescription(), Comunas.CUTATO.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUCHI.getDescription(), Comunas.VISSATI.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUITO_CUANAVALE.getDescription(), Comunas.BAIXO_LONGA.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUITO_CUANAVALE.getDescription(), Comunas.CUITO_CUANAVALE.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUITO_CUANAVALE.getDescription(), Comunas.LONGA.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.CUITO_CUANAVALE.getDescription(), Comunas.LUPIRE.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.DIRICO.getDescription(), Comunas.DIRICO.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.DIRICO.getDescription(), Comunas.MUCUSSO.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.DIRICO.getDescription(), Comunas.XAMAVERA.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.MAVINGA.getDescription(), Comunas.CUNJAMBA.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.MAVINGA.getDescription(), Comunas.CUTUILE.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.MAVINGA.getDescription(), Comunas.LUENGUE.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.MAVINGA.getDescription(), Comunas.MAVINGA.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.MENONGUE.getDescription(), Comunas.CAIUNDO.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.MENONGUE.getDescription(), Comunas.CUEIO.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.MENONGUE.getDescription(), Comunas.MENONGUE.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.MENONGUE.getDescription(), Comunas.MISSOMBO.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.NANCOVA.getDescription(), Comunas.NANCOVA.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.NANCOVA.getDescription(), Comunas.RITO.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.RIVUNGO.getDescription(), Comunas.LUIANA.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.RIVUNGO.getDescription(), Comunas.RIVUNGO.getDescription()));
        items.add(new Comuna(CUANDO_CUBANGO.getCode(), Municipios.RIVUNGO.getDescription(), Comunas.XIPUNDO.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CAHAMA.getDescription(), Comunas.CAHAMA.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CAHAMA.getDescription(), Comunas.OTCHINJAU.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUANHAMA.getDescription(), Comunas.EVALE.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUANHAMA.getDescription(), Comunas.MONGWA.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUANHAMA.getDescription(), Comunas.NEHONE_CAFIMA.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUANHAMA.getDescription(), Comunas.ONDJIVA.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUANHAMA.getDescription(), Comunas.TCHOMPORO_OXIMOLO.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUROCA.getDescription(), Comunas.CHITADO.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUROCA.getDescription(), Comunas.ONCOCUA.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUVELAI.getDescription(), Comunas.CALONGA.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUVELAI.getDescription(), Comunas.CUBATI.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUVELAI.getDescription(), Comunas.MUKOLONGODJO.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.CUVELAI.getDescription(), Comunas.MUPA.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.NAMACUNDE.getDescription(), Comunas.CHIEDE.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.NAMACUNDE.getDescription(), Comunas.NAMACUNDE.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.OMBANDJA.getDescription(), Comunas.HUMBE.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.OMBANDJA.getDescription(), Comunas.MUCOPE.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.OMBANDJA.getDescription(), Comunas.NAULILA.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.OMBANDJA.getDescription(), Comunas.OMBALA_YO_MUNGU.getDescription()));
        items.add(new Comuna(CUNENE.getCode(), Municipios.OMBANDJA.getDescription(), Comunas.XANGONGO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.BANGA.getDescription(), Comunas.ALDEIA_NOVA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.BANGA.getDescription(), Comunas.BANGA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.BANGA.getDescription(), Comunas.CACULO_CABACA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.BANGA.getDescription(), Comunas.CARIAMBA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.BOLONGONGO.getDescription(), Comunas.BOLONGONGO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.BOLONGONGO.getDescription(), Comunas.QUIQUIEMBA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.BOLONGONGO.getDescription(), Comunas.TERREIRO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.AMBACA.getDescription(), Comunas.BINDO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.AMBACA.getDescription(), Comunas.CAMABATELA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.AMBACA.getDescription(), Comunas.LUINGA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.AMBACA.getDescription(), Comunas.MAUA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.AMBACA.getDescription(), Comunas.TANGO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.CAMBAMBE.getDescription(), Comunas.DANGE_YA_MENHA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.CAMBAMBE.getDescription(), Comunas.DONDO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.CAMBAMBE.getDescription(), Comunas.MASSANGANO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.CAMBAMBE.getDescription(), Comunas.SAO_PEDRO_DA_QUILEMBA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.CAMBAMBE.getDescription(), Comunas.ZENZA_DO_ITOMBE.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.CAZENGO.getDescription(), Comunas.CANHOCA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.CAZENGO.getDescription(), Comunas.NDALATANDO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.GOLUNGO_ALTO.getDescription(), Comunas.CAMBONDO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.GOLUNGO_ALTO.getDescription(), Comunas.CERCA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.GOLUNGO_ALTO.getDescription(), Comunas.GOLUNGO_ALTO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.GOLUNGO_ALTO.getDescription(), Comunas.QUILUANJE.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.LUCALA.getDescription(), Comunas.LUCALA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.LUCALA.getDescription(), Comunas.QUIANGOMBE.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.NGONGUEMBO.getDescription(), Comunas.CAMAME.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.NGONGUEMBO.getDescription(), Comunas.CAVUNGA.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.NGONGUEMBO.getDescription(), Comunas.QUILOMBO_DOS_DEMBOS.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.QUICULUNGO.getDescription(), Comunas.QUICULUNGO.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.SAMBA_CAJU.getDescription(), Comunas.SAMBA_CAJU.getDescription()));
        items.add(new Comuna(CUANZA_NORTE.getCode(), Municipios.SAMBA_CAJU.getDescription(), Comunas.SAMBA_LUCALA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.AMBOIM.getDescription(), Comunas.ASSANGO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.AMBOIM.getDescription(), Comunas.GABELA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.CASSONGUE.getDescription(), Comunas.ATOME.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.CASSONGUE.getDescription(), Comunas.CASSONGUE.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.CASSONGUE.getDescription(), Comunas.DUMBI.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.CASSONGUE.getDescription(), Comunas.PAMBANGALA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.CELA.getDescription(), Comunas.QUISSANGA_CUNJO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.CELA.getDescription(), Comunas.SANGA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.CELA.getDescription(), Comunas.WAKU_KUNGO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.CONDA.getDescription(), Comunas.CONDA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.CONDA.getDescription(), Comunas.CUNJO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.EBO.getDescription(), Comunas.CONDE.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.EBO.getDescription(), Comunas.EBO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.EBO.getDescription(), Comunas.QUISSANJE.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.LIBOLO.getDescription(), Comunas.CABUTA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.LIBOLO.getDescription(), Comunas.CALULO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.LIBOLO.getDescription(), Comunas.MUNENGA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.LIBOLO.getDescription(), Comunas.QUISSONGO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.MUSSENDE.getDescription(), Comunas.MUSSENDE.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.MUSSENDE.getDescription(), Comunas.QUIENHA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.MUSSENDE.getDescription(), Comunas.SAO_LUCAS.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.PORTO_AMBOIM.getDescription(), Comunas.CAPOLO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.PORTO_AMBOIM.getDescription(), Comunas.PORTO_AMBOIM.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.QUIBALA.getDescription(), Comunas.CARIANGO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.QUIBALA.getDescription(), Comunas.DALA_CACHIBO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.QUIBALA.getDescription(), Comunas.LONHE.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.QUIBALA.getDescription(), Comunas.QUIBALA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.QUILENDA.getDescription(), Comunas.QUILENDA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.QUILENDA.getDescription(), Comunas.QUIRIMBO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.SELES.getDescription(), Comunas.AMBOIVA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.SELES.getDescription(), Comunas.BOTERA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.SELES.getDescription(), Comunas.SELES.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.SUMBE.getDescription(), Comunas.GANGULA.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.SUMBE.getDescription(), Comunas.GUNGO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.SUMBE.getDescription(), Comunas.QUICOMBO.getDescription()));
        items.add(new Comuna(CUANZA_SUL.getCode(), Municipios.SUMBE.getDescription(), Comunas.SUMBE.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CACONDA.getDescription(), Comunas.CACONDA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CACONDA.getDescription(), Comunas.CUSSE.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CACONDA.getDescription(), Comunas.GUNGUE.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CACONDA.getDescription(), Comunas.UABA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CACULA.getDescription(), Comunas.CACULA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CACULA.getDescription(), Comunas.CHITUTO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CACULA.getDescription(), Comunas.TCHICUAQUEIA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CACULA.getDescription(), Comunas.VITIVIVALI.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CALUQUEMBE.getDescription(), Comunas.CALEPI.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CALUQUEMBE.getDescription(), Comunas.CALUQUEMBE.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CALUQUEMBE.getDescription(), Comunas.NGOLA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CHIBIA.getDescription(), Comunas.CAPUNDA_CAVILONGO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CHIBIA.getDescription(), Comunas.CHIBIA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CHIBIA.getDescription(), Comunas.JAU.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CHIBIA.getDescription(), Comunas.QUIHITA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CHICOMBA.getDescription(), Comunas.CHICOMBA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CHICOMBA.getDescription(), Comunas.CUTENDA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CHIPINDO.getDescription(), Comunas.BAMBI.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CHIPINDO.getDescription(), Comunas.CHIPINDO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CUVANGO.getDescription(), Comunas.CUVANGO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CUVANGO.getDescription(), Comunas.GALANGUE.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.CUVANGO.getDescription(), Comunas.VICUNGO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.GAMBOS.getDescription(), Comunas.CHIANGE.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.GAMBOS.getDescription(), Comunas.CHIMBEMBA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.HUMPATA.getDescription(), Comunas.HUMPATA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.JAMBA.getDescription(), Comunas.CASSINGA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.JAMBA.getDescription(), Comunas.DONGO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.JAMBA.getDescription(), Comunas.JAMBA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.LUBANGO.getDescription(), Comunas.ARIMBA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.LUBANGO.getDescription(), Comunas.HOQUE.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.LUBANGO.getDescription(), Comunas.HUILA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.LUBANGO.getDescription(), Comunas.LUBANGO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.MATALA.getDescription(), Comunas.CAPELONGO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.MATALA.getDescription(), Comunas.MATALA.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.MATALA.getDescription(), Comunas.MULONDO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.QUILENGUES.getDescription(), Comunas.DINDE.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.QUILENGUES.getDescription(), Comunas.IMPULO.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.QUILENGUES.getDescription(), Comunas.QUILENGUES.getDescription()));
        items.add(new Comuna(HUILA.getCode(), Municipios.QUIPUNGO.getDescription(), Comunas.QUIPUNGO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.BAILUNDO.getDescription(), Comunas.BAILUNDO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.BAILUNDO.getDescription(), Comunas.BIMBE.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.BAILUNDO.getDescription(), Comunas.HENGUE.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.BAILUNDO.getDescription(), Comunas.LUNGE.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.BAILUNDO.getDescription(), Comunas.LUVEMBA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CAALA.getDescription(), Comunas.CAALA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CAALA.getDescription(), Comunas.CALENGA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CAALA.getDescription(), Comunas.CATATA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CAALA.getDescription(), Comunas.CUIMA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CACHIUNGO.getDescription(), Comunas.CACHIUNGO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CACHIUNGO.getDescription(), Comunas.CHINHAMA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CACHIUNGO.getDescription(), Comunas.CHIUMBO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CHICALA_CHOLOANGA.getDescription(), Comunas.CHICALA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CHICALA_CHOLOANGA.getDescription(), Comunas.MBAVE.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CHICALA_CHOLOANGA.getDescription(), Comunas.SAMBO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CHICALA_CHOLOANGA.getDescription(), Comunas.SAMBOTO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CHINJENJE.getDescription(), Comunas.CHIACA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.CHINJENJE.getDescription(), Comunas.CHINJENJE.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.ECUNHA.getDescription(), Comunas.ECUNHA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.ECUNHA.getDescription(), Comunas.QUIPEIO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.HUAMBO.getDescription(), Comunas.CALIMA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.HUAMBO.getDescription(), Comunas.CHIPIPA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.HUAMBO.getDescription(), Comunas.HUAMBO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.LONDUIMBALI.getDescription(), Comunas.ALTO_HAMA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.LONDUIMBALI.getDescription(), Comunas.CUMBIRA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.LONDUIMBALI.getDescription(), Comunas.GALANGA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.LONDUIMBALI.getDescription(), Comunas.LONDUIMBALI.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.LONDUIMBALI.getDescription(), Comunas.USSOQUE.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.LONGONJO.getDescription(), Comunas.CHILATA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.LONGONJO.getDescription(), Comunas.IAVA_CATABOLA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.LONGONJO.getDescription(), Comunas.LEPI.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.LONGONJO.getDescription(), Comunas.LONGONJO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.MUNGO.getDescription(), Comunas.CAMBUENGO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.MUNGO.getDescription(), Comunas.MUNGO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.UCUMA.getDescription(), Comunas.CACOMA.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.UCUMA.getDescription(), Comunas.MUNDUNDO.getDescription()));
        items.add(new Comuna(HUAMBO.getCode(), Municipios.UCUMA.getDescription(), Comunas.UCUMA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.BELAS.getDescription(), Comunas.BARRA_DO_CUANZA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.BELAS.getDescription(), Comunas.CABOLOMBO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.BELAS.getDescription(), Comunas.KILAMBA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.BELAS.getDescription(), Comunas.MORRO_DOS_VEADOS.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.BELAS.getDescription(), Comunas.QUENGUELA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.BELAS.getDescription(), Comunas.RAMIROS.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.BELAS.getDescription(), Comunas.VILA_VERDE.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CACUACO.getDescription(), Comunas.CACUACO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CACUACO.getDescription(), Comunas.FUNDA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CACUACO.getDescription(), Comunas.KIKOLO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CACUACO.getDescription(), Comunas.MULENVOS_DE_BAIXO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CACUACO.getDescription(), Comunas.SEQUELE.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CAZENGA.getDescription(), Comunas.ONZE_DE_NOVEMBRO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CAZENGA.getDescription(), Comunas.CAZENGA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CAZENGA.getDescription(), Comunas.HOJI_YA_HENDA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CAZENGA.getDescription(), Comunas.KALAWENDA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CAZENGA.getDescription(), Comunas.KIMA_KIEZA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.CAZENGA.getDescription(), Comunas.TALA_HADI.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.ICOLO_BENGO.getDescription(), Comunas.BELA_VISTA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.ICOLO_BENGO.getDescription(), Comunas.BOM_JESUS.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.ICOLO_BENGO.getDescription(), Comunas.CABIRI.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.ICOLO_BENGO.getDescription(), Comunas.CACULO_CAHANGO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.ICOLO_BENGO.getDescription(), Comunas.CASSONECA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.ICOLO_BENGO.getDescription(), Comunas.CATETE.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.ICOLO_BENGO.getDescription(), Comunas.QUIMINHA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.KILAMBA_KIAXI.getDescription(), Comunas.GOLFE.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.KILAMBA_KIAXI.getDescription(), Comunas.NOVA_VIDA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.KILAMBA_KIAXI.getDescription(), Comunas.PALANCA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.KILAMBA_KIAXI.getDescription(), Comunas.SAPU.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.LUANDA.getDescription(), Comunas.INGOMBOTA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.LUANDA.getDescription(), Comunas.MAIANGA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.LUANDA.getDescription(), Comunas.NEVES_BENDINHA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.LUANDA.getDescription(), Comunas.NGOLA_KILUANJE.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.LUANDA.getDescription(), Comunas.RANGEL.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.LUANDA.getDescription(), Comunas.SAMBA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.LUANDA.getDescription(), Comunas.SAMBIZANGA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.QUICAMA.getDescription(), Comunas.CABOLEDO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.QUICAMA.getDescription(), Comunas.DEMBA_CHIO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.QUICAMA.getDescription(), Comunas.MUMBONDO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.QUICAMA.getDescription(), Comunas.MUXIMA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.QUICAMA.getDescription(), Comunas.QUIXINGE.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.TALATONA.getDescription(), Comunas.BENFICA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.TALATONA.getDescription(), Comunas.CAMAMA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.TALATONA.getDescription(), Comunas.CIDADE_UNIVERSITARIA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.TALATONA.getDescription(), Comunas.FUTUNGO_DE_BELAS.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.TALATONA.getDescription(), Comunas.LAR_DO_PATRIOTA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.TALATONA.getDescription(), Comunas.MUSSULO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.TALATONA.getDescription(), Comunas.TALATONA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.VIANA.getDescription(), Comunas.BAIA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.VIANA.getDescription(), Comunas.CALUMBO.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.VIANA.getDescription(), Comunas.ESTALAGEM.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.VIANA.getDescription(), Comunas.KIKUXI.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.VIANA.getDescription(), Comunas.VIANA.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.VIANA.getDescription(), Comunas.VILA_FLOR.getDescription()));
        items.add(new Comuna(LUANDA.getCode(), Municipios.VIANA.getDescription(), Comunas.ZANGO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CAMBULO.getDescription(), Comunas.CACHIMO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CAMBULO.getDescription(), Comunas.CAMBULO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CAMBULO.getDescription(), Comunas.CANZAR.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CAMBULO.getDescription(), Comunas.LUIA.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CAPENDA_CAMULEMBA.getDescription(), Comunas.CAPENDA_CAMULEMBA.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CAPENDA_CAMULEMBA.getDescription(), Comunas.XINGE.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CAUNGULA.getDescription(), Comunas.CAMAXILO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CAUNGULA.getDescription(), Comunas.CAUNGULA.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CHITATO.getDescription(), Comunas.CAMISSOMBO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CHITATO.getDescription(), Comunas.CHITATO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CHITATO.getDescription(), Comunas.CHITATO_COMUNA.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CHITATO.getDescription(), Comunas.CHITATO_DISTRITO_URBANO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CHITATO.getDescription(), Comunas.DUNDO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CHITATO.getDescription(), Comunas.LUACHIMO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CHITATO.getDescription(), Comunas.MUSSUNGUE.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CUANGO.getDescription(), Comunas.CUANGO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CUANGO.getDescription(), Comunas.LUREMO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CUILO.getDescription(), Comunas.CALUANGO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.CUILO.getDescription(), Comunas.CUILO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.LOVUA.getDescription(), Comunas.LOVUA.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.LUBALO.getDescription(), Comunas.LUANGUE.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.LUBALO.getDescription(), Comunas.LUBALO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.LUBALO.getDescription(), Comunas.MUVULUEGE.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.LUCAPA.getDescription(), Comunas.CAPAIA.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.LUCAPA.getDescription(), Comunas.LUCAPA.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.LUCAPA.getDescription(), Comunas.XA_CASSAU.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.XA_MUTEBA.getDescription(), Comunas.CASSANJE_CALUCALA.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.XA_MUTEBA.getDescription(), Comunas.IONGO.getDescription()));
        items.add(new Comuna(LUNDA_NORTE.getCode(), Municipios.XA_MUTEBA.getDescription(), Comunas.XA_MUTEBA.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.CACOLO.getDescription(), Comunas.ALTO_CHICAPA.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.CACOLO.getDescription(), Comunas.CACOLO.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.CACOLO.getDescription(), Comunas.CUCUMBI.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.CACOLO.getDescription(), Comunas.XASSENGUE.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.DALA.getDescription(), Comunas.CAZAGE.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.DALA.getDescription(), Comunas.DALA.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.DALA.getDescription(), Comunas.LUMA_CASSAI.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.MUCONDA.getDescription(), Comunas.CASSAI.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.MUCONDA.getDescription(), Comunas.CHILUAGE.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.MUCONDA.getDescription(), Comunas.MUCONDA.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.MUCONDA.getDescription(), Comunas.MURIEGE.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.SAURIMO.getDescription(), Comunas.MONA_QUIMBUNDO.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.SAURIMO.getDescription(), Comunas.SAURIMO.getDescription()));
        items.add(new Comuna(LUNDA_SUL.getCode(), Municipios.SAURIMO.getDescription(), Comunas.SOMBO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CACUSO.getDescription(), Comunas.CACUSO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CACUSO.getDescription(), Comunas.LOMBE.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CACUSO.getDescription(), Comunas.PUNGU_A_NDONGO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CACUSO.getDescription(), Comunas.QUIZENGA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CACUSO.getDescription(), Comunas.SOQUECO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CAHOMBO.getDescription(), Comunas.CAHOMBO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CAHOMBO.getDescription(), Comunas.CAMBO_SUINGINGE.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CAHOMBO.getDescription(), Comunas.MBANJI_YA_NGOLA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CAHOMBO.getDescription(), Comunas.MICANDA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CALANDULA.getDescription(), Comunas.CALANDULA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CALANDULA.getDescription(), Comunas.CATECO_CANGOLA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CALANDULA.getDescription(), Comunas.COTA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CALANDULA.getDescription(), Comunas.CUALE.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CALANDULA.getDescription(), Comunas.QUINJE.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CAMBUNDI_CATEMBO.getDescription(), Comunas.CAMBUNDI_CATEMBO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CAMBUNDI_CATEMBO.getDescription(), Comunas.DUMBA_CAMBANGO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CAMBUNDI_CATEMBO.getDescription(), Comunas.QUITAPA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CAMBUNDI_CATEMBO.getDescription(), Comunas.TALAMUNGONGO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CANGANDALA.getDescription(), Comunas.BEMBO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CANGANDALA.getDescription(), Comunas.CANGANDALA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CANGANDALA.getDescription(), Comunas.CARIBO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.CANGANDALA.getDescription(), Comunas.CULAMAGIA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.KIWABA_NZOJI.getDescription(), Comunas.KIWABA_NZOJI.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.KIWABA_NZOJI.getDescription(), Comunas.MUFUMA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.KUNDA_DYA_BAZE.getDescription(), Comunas.KUNDA_DYA_BAZE.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.KUNDA_DYA_BAZE.getDescription(), Comunas.LEMBA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.KUNDA_DYA_BAZE.getDescription(), Comunas.MILANDO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.LUQUEMBO.getDescription(), Comunas.CAPUNDA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.LUQUEMBO.getDescription(), Comunas.CUNGA_PALANGA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.LUQUEMBO.getDescription(), Comunas.DOMBO_WA_ZANGA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.LUQUEMBO.getDescription(), Comunas.LUQUEMBO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.LUQUEMBO.getDescription(), Comunas.QUIMBANGO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.LUQUEMBO.getDescription(), Comunas.RIMBA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MALANJE.getDescription(), Comunas.CAMBAXE.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MALANJE.getDescription(), Comunas.MALANJE.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MALANJE.getDescription(), Comunas.NGOLA_LUIJI.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MARIMBA.getDescription(), Comunas.CABOMBO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MARIMBA.getDescription(), Comunas.MARIMBA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MARIMBA.getDescription(), Comunas.TEMBO_ALUMA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MASSANGO.getDescription(), Comunas.MASSANGO.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MASSANGO.getDescription(), Comunas.QUIHUHU.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MASSANGO.getDescription(), Comunas.QUINGUENGUE.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MUCARI.getDescription(), Comunas.CACULAMA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MUCARI.getDescription(), Comunas.CATALA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MUCARI.getDescription(), Comunas.CAXINGA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.MUCARI.getDescription(), Comunas.MUQUIXE.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.QUELA.getDescription(), Comunas.BANGALAS.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.QUELA.getDescription(), Comunas.MOMA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.QUELA.getDescription(), Comunas.QUELA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.QUELA.getDescription(), Comunas.XANDEL.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.QUIRIMA.getDescription(), Comunas.QUIRIMA.getDescription()));
        items.add(new Comuna(MALANJE.getCode(), Municipios.QUIRIMA.getDescription(), Comunas.SAUTAR.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.ALTO_ZAMBEZE.getDescription(), Comunas.CAIANDA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.ALTO_ZAMBEZE.getDescription(), Comunas.CALUNDA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.ALTO_ZAMBEZE.getDescription(), Comunas.CAZOMBO.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.ALTO_ZAMBEZE.getDescription(), Comunas.LOVUA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.ALTO_ZAMBEZE.getDescription(), Comunas.LUMBALA_CAQUENGUE.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.ALTO_ZAMBEZE.getDescription(), Comunas.MACONDO.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.ALTO_ZAMBEZE.getDescription(), Comunas.NANA_CANDUNDO.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.BUNDAS.getDescription(), Comunas.CHIUME.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.BUNDAS.getDescription(), Comunas.LUMBALA_NGUIMBO.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.BUNDAS.getDescription(), Comunas.LUTEMBO.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.BUNDAS.getDescription(), Comunas.LUVUEI.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.BUNDAS.getDescription(), Comunas.MUSSUMA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.BUNDAS.getDescription(), Comunas.NINDA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.BUNDAS.getDescription(), Comunas.SESSA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.CAMANONGUE.getDescription(), Comunas.CAMANONGUE.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.CAMEIA.getDescription(), Comunas.LUMEGE.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LEUA.getDescription(), Comunas.LEUA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LEUA.getDescription(), Comunas.LIANGONGO.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LUACANO.getDescription(), Comunas.LAGO_DILOLO.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LUACANO.getDescription(), Comunas.LUACANO.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LUAU.getDescription(), Comunas.LUAU.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LUCHAZES.getDescription(), Comunas.CANGAMBA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LUCHAZES.getDescription(), Comunas.CANGOMBE.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LUCHAZES.getDescription(), Comunas.CASSAMBA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LUCHAZES.getDescription(), Comunas.MUIE.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.LUCHAZES.getDescription(), Comunas.TEMPUE.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.MOXICO.getDescription(), Comunas.CACHIPOQUE.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.MOXICO.getDescription(), Comunas.LUCUSSE.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.MOXICO.getDescription(), Comunas.LUENA.getDescription()));
        items.add(new Comuna(MOXICO.getCode(), Municipios.MOXICO.getDescription(), Comunas.MUANGAI.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.BIBALA.getDescription(), Comunas.BIBALA.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.BIBALA.getDescription(), Comunas.CAITOU.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.BIBALA.getDescription(), Comunas.CAPANGOMBE.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.BIBALA.getDescription(), Comunas.LOLA.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.CAMUCUIO.getDescription(), Comunas.CAMUCUIU.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.CAMUCUIO.getDescription(), Comunas.CHINGO.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.CAMUCUIO.getDescription(), Comunas.MAMUE.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.MOCAMEDES.getDescription(), Comunas.BENTIABA.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.MOCAMEDES.getDescription(), Comunas.FORTE_SANTA_RITA.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.MOCAMEDES.getDescription(), Comunas.LUCIRA.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.MOCAMEDES.getDescription(), Comunas.MOCAMEDES.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.TOMBWA.getDescription(), Comunas.BAIA_DOS_TIGRES.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.TOMBWA.getDescription(), Comunas.IONA.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.TOMBWA.getDescription(), Comunas.TOMBWA.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.VIREI.getDescription(), Comunas.CAINDE.getDescription()));
        items.add(new Comuna(NAMIBE.getCode(), Municipios.VIREI.getDescription(), Comunas.VIREI.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.ALTO_CAUALE.getDescription(), Comunas.BENGO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.ALTO_CAUALE.getDescription(), Comunas.CAIONGO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.ALTO_CAUALE.getDescription(), Comunas.CANGOLA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.AMBUILA.getDescription(), Comunas.NOVA_AMBUILA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.AMBUILA.getDescription(), Comunas.QUIPEDRO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.BEMBE.getDescription(), Comunas.BEMBE.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.BEMBE.getDescription(), Comunas.LUCUNGA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.BEMBE.getDescription(), Comunas.MABAIA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.BUENGAS.getDescription(), Comunas.BUENGA_SUL.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.BUENGAS.getDescription(), Comunas.CUILO_CAMBOSO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.BUENGAS.getDescription(), Comunas.NOVA_ESPERANCA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.BUNGO.getDescription(), Comunas.BUNGO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.DAMBA.getDescription(), Comunas.CAMATAMBO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.DAMBA.getDescription(), Comunas.DAMBA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.DAMBA.getDescription(), Comunas.LEMBOA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.DAMBA.getDescription(), Comunas.NSOSSO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.DAMBA.getDescription(), Comunas.PETECUSSO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.DANGE_QUITEXE.getDescription(), Comunas.ALDEIA_VICOSA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.DANGE_QUITEXE.getDescription(), Comunas.CAMBAMBA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.DANGE_QUITEXE.getDescription(), Comunas.QUITEXE.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.DANGE_QUITEXE.getDescription(), Comunas.VISTA_ALEGRE.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MAQUELA_DO_ZOMBO.getDescription(), Comunas.BEU.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MAQUELA_DO_ZOMBO.getDescription(), Comunas.CUILO_FUTA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MAQUELA_DO_ZOMBO.getDescription(), Comunas.MAQUELA_DO_ZOMBO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MAQUELA_DO_ZOMBO.getDescription(), Comunas.QUIBOCOLO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MAQUELA_DO_ZOMBO.getDescription(), Comunas.SACANDICA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MILUNGA.getDescription(), Comunas.MACOCOLA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MILUNGA.getDescription(), Comunas.MACOLO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MILUNGA.getDescription(), Comunas.MASSAU.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MILUNGA.getDescription(), Comunas.MILUNGA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MUCABA.getDescription(), Comunas.MUCABA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.MUCABA.getDescription(), Comunas.UANDO_MUCABA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.NEGAGE.getDescription(), Comunas.DIMUCA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.NEGAGE.getDescription(), Comunas.NEGAGE.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.NEGAGE.getDescription(), Comunas.QUISSEQUE.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.POMBO.getDescription(), Comunas.ALFANDEGA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.POMBO.getDescription(), Comunas.CUILO_POMBO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.POMBO.getDescription(), Comunas.SANZA_POMBO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.POMBO.getDescription(), Comunas.UAMBA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.PURI.getDescription(), Comunas.PURI.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.QUIMBELE.getDescription(), Comunas.ALTO_ZAZA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.QUIMBELE.getDescription(), Comunas.CUANGO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.QUIMBELE.getDescription(), Comunas.ICOCA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.QUIMBELE.getDescription(), Comunas.QUIMBELE.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.SONGO.getDescription(), Comunas.QUIVUENGA.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.SONGO.getDescription(), Comunas.SONGO.getDescription()));
        items.add(new Comuna(UIGE.getCode(), Municipios.UIGE.getDescription(), Comunas.UIGE.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.CUIMBA.getDescription(), Comunas.BUELA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.CUIMBA.getDescription(), Comunas.CUIMBA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.CUIMBA.getDescription(), Comunas.LUVACA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.CUIMBA.getDescription(), Comunas.SERRA_DA_CANDA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.MBANZA_KONGO.getDescription(), Comunas.QUIENDE.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.MBANZA_KONGO.getDescription(), Comunas.CALAMBATA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.MBANZA_KONGO.getDescription(), Comunas.CALUCA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.MBANZA_KONGO.getDescription(), Comunas.LUVO.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.MBANZA_KONGO.getDescription(), Comunas.MADIMBA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.MBANZA_KONGO.getDescription(), Comunas.MBANZA_KONGO.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.MBANZA_KONGO.getDescription(), Comunas.QUIENDE.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.NOQUI.getDescription(), Comunas.LUFICO.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.NOQUI.getDescription(), Comunas.MPALA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.NOQUI.getDescription(), Comunas.NOQUI.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.NZETO.getDescription(), Comunas.MUSSERRA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.NZETO.getDescription(), Comunas.NZETO.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.NZETO.getDescription(), Comunas.QUIBALA_NORTE.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.NZETO.getDescription(), Comunas.QUINDEJE.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.SOYO.getDescription(), Comunas.MANGUE_GRANDE.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.SOYO.getDescription(), Comunas.PEDRA_DE_FEITICO.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.SOYO.getDescription(), Comunas.QUELO.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.SOYO.getDescription(), Comunas.SOYO.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.SOYO.getDescription(), Comunas.SUMBA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.TOMBOCO.getDescription(), Comunas.QUINSIMBA.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.TOMBOCO.getDescription(), Comunas.QUINZAU.getDescription()));
        items.add(new Comuna(ZAIRE.getCode(), Municipios.TOMBOCO.getDescription(), Comunas.TOMBOCO.getDescription()));

        return items;
    }

    public static String validarMunicipioPeloDistritoUrbanoOuComuna(String codigo) {

        String municipio = null;
        List<Comuna> listaProvinciaMunicipioDistComuna = Comunas().stream().filter(i -> i.getCodigo().equalsIgnoreCase(codigo)).collect(Collectors.toList());
        for (Comuna municipality : listaProvinciaMunicipioDistComuna) {
            municipio = municipality.getCodigoMunicipio();
        }
        return municipio;

    }

    public static String validarProvinciaPeloMunicipioEDistritoUrbanoOuComuna(String codigoMunicipio, String codigoDistritoUrbanoOuComuna) {

        String provincia = null;
        List<Comuna> listaProvinceMunicipioDistComuna = Comunas().stream().filter(i -> i.getCodigoMunicipio().equalsIgnoreCase(codigoMunicipio) && i.getCodigo().equalsIgnoreCase(codigoDistritoUrbanoOuComuna)).collect(Collectors.toList());
        if (!listaProvinceMunicipioDistComuna.isEmpty()) {
            for (Comuna province : listaProvinceMunicipioDistComuna) {
                provincia = province.getCodigoProvincia();
            }
        }
        return provincia;
    }

}
