package nzuzi.joao.criacao_consulta_numero_bi.enumerate;

import lombok.Getter;
import lombok.Setter;

public enum Comunas {

    //Comunas de Benguela
    CALOHANGA("CALOHANGA"),
    DOMBEGRANDE("DOMBE GRANDE"),
    BAIA_FARTA("BAÍA FARTA"),
    EQUIMINA("EQUIMINA"),
    BALOMBO("BALOMBO"),
    CHINDUMBO("CHINDUMBO"),
    CHINGONGO("CHINGONGO"),
    MACAMOMBOLO("MACA MOMBOLO"),
    BENGUELA("BENGUELA"),
    BOCOIO("BOCOIO"),
    CHILA("CHILA"),
    CUBAL_DO_LUMBO("CUBAL DO LUMBO (CAVIMBE)"),
    MONTE_BELO("MONTE BELO"),
    PASSE("PASSE"),
    CAIAVE("CAIAVE"),
    CAIMBAMBO("CAIMBAMBO"),
    CANHAMELA("CANHAMELA"),
    CATENGUE("CATENGUE"),
    VIANGOMBE("VIANGOMBE"),
    BIOPIO("BIÓPIO"),
    CATUMBELA("CATUMBELA"),
    GAMA("GAMA"),
    PRAIA_BEBE("PRAIA BEBÉ"),
    BOLONGUERA("BOLONGUERA"),
    CAMUINE("CAMUINE"),
    CHONGOROI("CHONGORÓI"),
    CAPUPA("CAPUPA"),
    CUBAL("CUBAL"),
    IAMBALA("IAMBALA"),
    TUMBULO("TUMBULO"),
    BABAERA("BABAERA"),
    CASSEQUE("CASSEQUE"),
    CHICUMA("CHICUMA"),
    EBANGA("EBANGA"),
    GANDA("GANDA"),
    CANATA("CANATA"),
    CANJALA("CANJALA"),
    EGIPTO_PRAIA("EGIPTO PRAIA (BALABAIA)"),
    LOBITO("LOBITO"),

    //Comunas do Bié
    ANDULO("ANDULO"),

    CALUCINGA("CALUCINGA"),

    CASSUMBE("CASSUMBE"),

    CHIVAULO("CHIVAÚLO"),

    CAMACUPA("CAMACUPA"),

    CUANZA("CUANZA"),

    MUINHA("MUINHA (ST. ANTº DA MUINHA)"),

    RINGOMA("RINGOMA"),

    UMPULO("UMPULO"),

    CAIUERA("CAIUERA"),

    CATABOLA("CATABOLA"),

    CHIPETA("CHIPETA"),

    CHIUCA("CHIUCA"),

    SANDE("SANDE"),

    CANGOTE("CANGOTE"),

    CHINGUAR("CHINGUAR"),

    CUTATO("CUTATO"),

    CACHINGUES("CACHINGUES"),

    CHITEMBO("CHITEMBO"),

    MALENGUE("MALENGUE"),

    MUMBUE("MUMBUÉ"),

    MUTUMBO("MUTUMBO"),

    SOMA_CUANZA("SOMA CUANZA"),

    CUEMBA("CUEMBA"),

    LUANDO("LUANDO"),

    MUNHANGO("MUNHANGO"),

    SACHINEMUNA("SACHINEMUNA"),

    CAMBANDUA("CAMBÂNDUA"),

    CHICALA("CHICALA"),

    CUITO("CUITO"),

    CUNJE("CUNJE"),

    TRUMBA("TRUMBA"),

    BELO_HORIZONTE("BELO HORIZONTE"),

    CUNHINGA("CUNHINGA"),

    CAIEI("CAIEI"),

    DANDO("DANDO"),

    GAMBA("GAMBA"),

    LUBIA("LÚBIA"),

    NHAREA("NHARÊA"),

    AMBRIZ("AMBRIZ"),

    TABI("TABI"),

    BULA_ATUMBA("BULA-ATUMBA"),

    QUIAGE("QUIAGE"),

    BARRA_DO_DANDE("BARRA DO DANDE"),

    CAXITO("CAXITO"),

    MABUBAS("MABUBAS"),

    QUICABO("QUICABO"),

    UCUA("ÚCUA"),

    COXE("COXE (SÃO JOSÉ DAS MATAS)"),

    PAREDES("PAREDES"),

    PIRI("PIRI"),

    QUIBAXE("QUIBAXE"),

    CAGE("CAGE (MAZUMBO)"),

    CANACASSALA("CANACASSALA"),

    GOMBE("GOMBE"),

    MUXALUANDO("MUXALUANDO"),

    QUICUNZO("QUICUNZO (MUCONDO)"),

    QUIXICO("QUIXICO"),

    ZALA("ZALA"),

    CAZUANGONGO("CAZUANGONGO"),
    PANGO_ALUQUEM("PANGO ALUQUÉM"),
    PANGOALUQUEM("PANGO-ALUQUÉM"),

    BELIZE("BELIZE"),

    LUALI("LUALI"),

    MICONJE("MICONJE"),

    BUCOZAU("BUCOZAU"),

    INHUCA("INHUCA"),

    NECUTO("NECUTO"),

    CABINDA("CABINDA"),

    MALEMBO("MALEMBO"),

    TANDO_ZINZE("TANDO ZINZE (FUBO)"),

    DINGE("DINGE"),

    CACONGO("CACONGO (LÂNDANA)"),

    MASSABI("MASSABI (CHICAMBA)"),

    CALAI("CALAI"),

    MAUE("MAUÉ"),

    MAVENGUE("MAVENGUE"),

    CAILA("CAÍLA"),

    CUANGAR("CUANGAR"),

    SAVATE("SAVATE"),

    CHINGUANJA("CHINGUANJA"),

    CUCHI("CUCHI"),

    VISSATI("VISSATI"),

    BAIXO_LONGA("BAIXO LONGA"),

    CUITO_CUANAVALE("CUITO CUANAVALE"),

    LONGA("LONGA"),

    LUPIRE("LUPIRE"),

    DIRICO("DIRICO"),

    MUCUSSO("MUCUSSO"),

    XAMAVERA("XAMAVERA"),

    CUNJAMBA("CUNJAMBA (DIMA)"),

    CUTUILE("CUTUILE"),

    LUENGUE("LUENGUE"),

    MAVINGA("MAVINGA"),

    CAIUNDO("CAIUNDO"),

    CUEIO("CUEIO"),

    MENONGUE("MENONGUE"),

    MISSOMBO("MISSOMBO"),

    NANCOVA("NANCOVA"),

    RITO("RITO"),

    LUIANA("LUIANA"),

    RIVUNGO("RIVUNGO"),

    XIPUNDO("XIPUNDO (GALANGA)"),

    CAHAMA("CAHAMA"),

    OTCHINJAU("OTCHINJAU"),

    EVALE("EVALE"),

    MONGWA("MÔNGWA"),

    NEHONE_CAFIMA("NEHONE CAFIMA"),

    ONDJIVA("ONDJIVA"),

    TCHOMPORO_OXIMOLO("TCHOMPORO OXIMOLO (EMBUNDO)"),

    CHITADO("CHITADO"),

    ONCOCUA("ONCÓCUA"),

    CALONGA("CALONGA (NAMPALA)"),

    CUBATI("CUBATI (CHISSUATA)"),

    MUKOLONGODJO("MUKOLONGODJO"),

    MUPA("MUPA"),

    CHIEDE("CHIEDE (MELUNGA)"),

    NAMACUNDE("NAMACUNDE"),

    HUMBE("HUMBE"),

    MUCOPE("MUCOPE"),

    NAULILA("NAULILA"),

    OMBALA_YO_MUNGU("OMBALA YO MUNGU"),

    XANGONGO("XANGONGO"),

    ALDEIA_NOVA("ALDEIA NOVA"),

    BANGA("BANGA"),

    CACULO_CABACA("CACULO CABAÇA"),

    CARIAMBA("CARIAMBA"),

    BOLONGONGO("BOLONGONGO"),

    QUIQUIEMBA("QUIQUIEMBA"),

    TERREIRO("TERREIRO"),

    BINDO("BINDO"),

    CAMABATELA("CAMABATELA"),

    LUINGA("LUINGA"),

    MAUA("MÁUA"),

    TANGO("TANGO"),

    DANGE_YA_MENHA("DANGE YA MENHA"),

    DONDO("DONDO"),

    MASSANGANO("MASSANGANO"),

    SAO_PEDRO_DA_QUILEMBA("SÃO PEDRO DA QUILEMBA"),

    ZENZA_DO_ITOMBE("ZENZA DO ITOMBE"),

    CANHOCA("CANHOCA"),

    NDALATANDO("NDALATANDO"),

    CAMBONDO("CAMBONDO"),

    CERCA("CÊRCA"),

    GOLUNGO_ALTO("GOLUNGO ALTO"),

    QUILUANJE("QUILUANJE"),

    QUIANGOMBE("QUIANGOMBE"),

    CAMAME("CAMAME"),

    CAVUNGA("CAVUNGA"),

    QUILOMBO_DOS_DEMBOS("QUILOMBO DOS DEMBOS"),

    QUICULUNGO("QUICULUNGO"),
    LUCALA("LUCALA"),
    SAMBA_CAJU("SAMBA CAJÚ"),
    SAMBA_LUCALA("SAMBA LUCALA"),

    ASSANGO("ASSANGO"),

    GABELA("GABELA"),

    ATOME("ATÓME"),

    CASSONGUE("CASSONGUE"),

    DUMBI("DUMBI"),

    PAMBANGALA("PAMBANGALA"),

    QUISSANGA_CUNJO("QUISSANGA CUNJO"),

    SANGA("SANGA"),

    WAKU_KUNGO("WAKU KUNGO"),

    CONDA("CONDA"),

    CUNJO("CUNJO"),

    CONDE("CONDÉ"),

    EBO("EBO"),

    QUISSANJE("QUISSANJE"),

    CABUTA("CABUTA"),

    CALULO("CALULO"),

    MUNENGA("MUNENGA"),

    QUISSONGO("QUISSONGO"),

    MUSSENDE("MUSSENDE"),

    QUIENHA("QUIENHA"),

    SAO_LUCAS("SÃO LUCAS"),

    CAPOLO("CAPOLO"),

    PORTO_AMBOIM("PORTO AMBOIM"),

    CARIANGO("CARIANGO"),

    DALA_CACHIBO("DALA CACHIBO"),

    LONHE("LONHE (GUNGO)"),

    QUIBALA("QUIBALA"),

    QUILENDA("QUILENDA"),

    QUIRIMBO("QUIRIMBO"),

    AMBOIVA("AMBOIVA"),

    BOTERA("BOTERA"),

    SELES("SELES"),

    GANGULA("GANGULA"),

    GUNGO("GUNGO"),

    QUICOMBO("QUICOMBO"),

    SUMBE("SUMBE"),

    CACONDA("CACONDA"),

    CUSSE("CUSSE"),

    GUNGUE("GUNGUE"),

    UABA("UABA"),

    CACULA("CACULA"),

    CHITUTO("CHITUTO"),

    TCHICUAQUEIA("TCHICUAQUEIA"),

    VITIVIVALI("VITI VIVALI"),

    CALEPI("CALEPI"),

    CALUQUEMBE("CALUQUEMBE"),

    NGOLA("NGOLA"),

    CAPUNDA_CAVILONGO("CAPUNDA CAVILONGO"),

    CHIBIA("CHIBIA"),

    JAU("JAU"),

    QUIHITA("QUIHITA"),

    CHICOMBA("CHICOMBA"),

    CUTENDA("CUTENDA"),

    BAMBI("BAMBI"),

    CHIPINDO("CHIPINDO"),

    CUVANGO("CUVANGO"),

    GALANGUE("GALANGUE"),

    VICUNGO("VICUNGO"),

    CHIANGE("CHIANGE"),

    CHIMBEMBA("CHIMBEMBA"),

    HUMPATA("HUMPATA"),

    CASSINGA("CASSINGA"),

    DONGO("DONGO"),

    JAMBA("JAMBA"),

    ARIMBA("ARIMBA"),

    HOQUE("HOQUE"),

    HUILA("HUÍLA"),

    LUBANGO("LUBANGO"),

    CAPELONGO("CAPELONGO"),

    MATALA("MATALA"),

    MULONDO("MULONDO"),

    DINDE("DINDE"),

    IMPULO("IMPULO"),

    QUILENGUES("QUILENGUES"),

    QUIPUNGO("QUIPUNGO"),

    BAILUNDO("BAILUNDO"),

    BIMBE("BIMBE"),

    HENGUE("HENGUE (CULULO)"),

    LUNGE("LUNGE"),

    LUVEMBA("LUVEMBA"),

    CAALA("CAÁLA"),

    CALENGA("CALENGA"),

    CATATA("CATATA (CATATA-A-NOVA)"),

    CUIMA("CUIMA"),

    CACHIUNGO("CACHIUNGO"),

    CHINHAMA("CHINHAMA"),

    CHIUMBO("CHIUMBO"),

    MBAVE("MBAVE"),

    SAMBO("SAMBO"),

    SAMBOTO("SAMBOTO"),

    CHIACA("CHIACA"),

    CHINJENJE("CHINJENJE"),

    ECUNHA("ECUNHA"),

    QUIPEIO("QUIPEIO"),

    CALIMA("CALIMA"),

    CHIPIPA("CHIPIPA"),

    HUAMBO("HUAMBO"),

    ALTO_HAMA("ALTO HAMA"),

    CUMBIRA("CUMBIRA (CATUCULUCA)"),

    GALANGA("GALANGA"),

    LONDUIMBALI("LONDUIMBALI"),

    USSOQUE("USSOQUE"),

    CHILATA("CHILATA (GOMBEALAMBA)"),

    IAVA_CATABOLA("IAVA (CATABOLA)"),

    LEPI("LÉPI"),

    LONGONJO("LONGONJO"),

    CAMBUENGO("CAMBUENGO"),

    MUNGO("MUNGO"),

    CACOMA("CACOMA"),

    MUNDUNDO("MUNDUNDO (ELEVA)"),

    UCUMA("UCUMA"),

    BARRA_DO_CUANZA("BARRA DO CUANZA"),

    CABOLOMBO("CABOLOMBO"),

    KILAMBA("KILAMBA"),

    MORRO_DOS_VEADOS("MORRO DOS VEADOS"),

    QUENGUELA("QUENGUELA"),

    RAMIROS("RAMIROS"),

    VILA_VERDE("VILA VERDE"),

    CACUACO("CACUACO"),

    FUNDA("FUNDA"),

    KIKOLO("KIKOLO"),

    MULENVOS_DE_BAIXO("MULENVOS DE BAIXO"),

    SEQUELE("SEQUELE"),
    ONZE_DE_NOVEMBRO("11 DE NOVEMBRO"),

    CAZENGA("CAZENGA"),

    HOJI_YA_HENDA("HOJI YA HENDA"),

    KALAWENDA("KALAWENDA"),

    KIMA_KIEZA("KIMA KIEZA"),

    TALA_HADI("TALA HADI"),

    BELA_VISTA("BELA VISTA"),

    BOM_JESUS("BOM JESUS"),

    CABIRI("CABIRI"),

    CACULO_CAHANGO("CACULO CAHANGO"),

    CASSONECA("CASSONECA"),

    CATETE("CATETE"),

    QUIMINHA("QUIMINHA"),

    GOLFE("GOLFE"),

    NOVA_VIDA("NOVA VIDA"),

    PALANCA("PALANCA"),

    SAPU("SAPÚ"),

    INGOMBOTA("INGOMBOTA"),

    MAIANGA("MAIANGA"),

    NEVES_BENDINHA("NEVES BENDINHA"),

    NGOLA_KILUANJE("NGOLA KILUANJE"),

    RANGEL("RANGEL"),

    SAMBA("SAMBA"),

    SAMBIZANGA("SAMBIZANGA"),

    CABOLEDO("CABOLEDO"),

    DEMBA_CHIO("DEMBA CHIO"),

    MUMBONDO("MUMBONDO"),

    MUXIMA("MUXIMA"),

    QUIXINGE("QUIXINGE"),

    BENFICA("BENFICA"),

    CAMAMA("CAMAMA"),

    CIDADE_UNIVERSITARIA("CIDADE UNIVERSITÁRIA"),

    FUTUNGO_DE_BELAS("FUTUNGO DE BELAS"),

    LAR_DO_PATRIOTA("LAR DO PATRIOTA"),

    MUSSULO("MUSSULO"),

    TALATONA("TALATONA"),

    BAIA("BAIA"),

    CALUMBO("CALUMBO"),

    ESTALAGEM("ESTALAGEM"),

    KIKUXI("KIKUXI"),

    VIANA("VIANA"),

    VILA_FLOR("VILA FLÔR"),

    ZANGO("ZANGO"),

    CACHIMO("CACHIMO"),

    CAMBULO("CAMBULO"),

    CANZAR("CANZAR"),

    LUIA("LUIA"),

    CAPENDA_CAMULEMBA("CAPENDA CAMULEMBA"),

    XINGE("XINGE"),

    CAMAXILO("CAMAXILO"),

    CAUNGULA("CAUNGULA"),

    CAMISSOMBO("CAMISSOMBO"),

    CAPAIA("CAPAIA"),

    CHITATO("CHITATO"),

    CHITATO_COMUNA("CHITATO (COMUNA)"),

    CHITATO_DISTRITO_URBANO("CHITATO (DISTRITO URBANO)"),

    DUNDO("DUNDO"),

    LUACHIMO("LUACHIMO"),

    MUSSUNGUE("MUSSUNGUE"),

    XA_CASSAU("XÁ CASSAU"),

    CUANGO("CUANGO"),

    LUREMO("LUREMO"),

    CALUANGO("CALUANGO"),

    CUILO("CUILO"),

    LUANGUE("LUANGUE"),

    LUBALO("LUBALO"),
    LUCAPA("LUCAPA"),

    MUVULUEGE("MUVULUEGE"),

    CASSANJE_CALUCALA("CASSANJE CALUCALA"),

    IONGO("IONGO"),

    XA_MUTEBA("XÁ MUTEBA"),

    ALTO_CHICAPA("ALTO CHICAPA"),

    CACOLO("CACOLO"),

    CUCUMBI("CUCUMBI"),

    XASSENGUE("XASSENGUE"),

    CAZAGE("CAZAGE"),

    DALA("DALA"),

    LUMA_CASSAI("LUMA CASSAI"),

    CASSAI("CASSAI"),

    CHILUAGE("CHILUAGE"),

    MUCONDA("MUCONDA"),

    MURIEGE("MURIEGE"),

    MONA_QUIMBUNDO("MONA QUIMBUNDO"),

    SAURIMO("SAURIMO"),

    SOMBO("SOMBO"),

    CACUSO("CACUSO"),

    LOMBE("LOMBE"),

    PUNGU_A_NDONGO("PUNGU A NDONGO"),

    QUIZENGA("QUIZENGA"),

    SOQUECO("SOQUECO"),

    CAHOMBO("CAHOMBO"),

    CAMBO_SUINGINGE("CAMBO SUINGINGE"),

    MBANJI_YA_NGOLA("MBANJI YA NGOLA"),

    MICANDA("MICANDA"),

    CALANDULA("CALANDULA"),

    CATECO_CANGOLA("CATECO CANGOLA"),

    COTA("COTA"),

    CUALE("CUALE"),

    QUINJE("QUINJE"),

    CAMBUNDI_CATEMBO("CAMBUNDI CATEMBO"),

    DUMBA_CAMBANGO("DUMBA CAMBANGO"),

    QUITAPA("QUITAPA"),

    TALAMUNGONGO("TALAMUNGONGO"),

    BEMBO("BEMBO"),

    CANGANDALA("CANGANDALA"),

    CARIBO("CARIBO"),

    CULAMAGIA("CULAMAGIA"),

    KIWABA_NZOJI("KIWABA_NZOJI"),

    MUFUMA("MUFUMA"),

    KUNDA_DYA_BAZE("KUNDA DYA BAZE"),

    LEMBA("LEMBA"),

    MILANDO("MILANDO"),

    CAPUNDA("CAPUNDA"),

    CUNGA_PALANGA("CUNGA PALANGA"),

    DOMBO_WA_ZANGA("DOMBO WA ZANGA"),

    LUQUEMBO("LUQUEMBO"),

    QUIMBANGO("QUIMBANGO"),

    RIMBA("RIMBA"),

    CAMBAXE("CAMBAXE"),

    MALANJE("MALANJE"),

    NGOLA_LUIJI("NGOLA LUIJI"),

    CABOMBO("CABOMBO"),

    MARIMBA("MARIMBA"),

    TEMBO_ALUMA("TEMBO ALUMA (MANGANDO)"),

    MASSANGO("MASSANGO"),

    QUIHUHU("QUIHUHU"),

    QUINGUENGUE("QUINGUENGUE"),

    CACULAMA("CACULAMA"),

    CATALA("CATALA"),

    CAXINGA("CAXINGA"),

    MUQUIXE("MUQUIXE"),

    BANGALAS("BÂNGALAS"),

    MOMA("MOMA"),

    QUELA("QUELA"),

    XANDEL("XANDEL"),

    QUIRIMA("QUIRIMA"),

    SAUTAR("SAUTAR"),

    CAIANDA("CAIANDA"),

    CALUNDA("CALUNDA"),

    CAZOMBO("CAZOMBO"),

    LOVUA("LÓVUA"),

    LUMBALA_CAQUENGUE("LUMBALA CAQUENGUE"),

    MACONDO("MACONDO"),

    NANA_CANDUNDO("NANA CANDUNDO (CAVUNGO)"),

    CHIUME("CHIUME"),

    LUMBALA_NGUIMBO("LUMBALA NGUIMBO"),

    LUTEMBO("LUTEMBO"),

    LUVUEI("LUVUEI (LUMA)"),

    MUSSUMA("MUSSUMA"),

    NINDA("NINDA"),

    SESSA("SESSA"),

    CAMANONGUE("CAMANONGUE"),

    LUMEGE("CAMEIA (LUMEGE)"),

    LEUA("LÉUA"),

    LIANGONGO("LIANGONGO"),

    LAGO_DILOLO("LAGO-DILOLO"),

    LUACANO("LUACANO"),

    LUAU("LUAU"),

    CANGAMBA("CANGAMBA"),

    CANGOMBE("CANGOMBE"),

    CASSAMBA("CASSAMBA"),

    MUIE("MUIÉ"),

    TEMPUE("TEMPUÉ (ALTO CUITO)"),

    CACHIPOQUE("CACHIPOQUE (CANGUMBE)"),

    LUCUSSE("LUCUSSE"),

    LUENA("LUENA"),

    MUANGAI("MUANGAI (LUTUAI)"),

    BIBALA("BIBALA"),

    CAITOU("CAITOU"),

    CAPANGOMBE("CAPANGOMBE (MUNHINO)"),

    LOLA("LOLA"),

    CAMUCUIU("CAMUCUIU"),

    CHINGO("CHINGO"),

    MAMUE("MAMUÉ (CHINQUITE)"),

    BENTIABA("BENTIABA"),

    FORTE_SANTA_RITA("FORTE SANTA RITA"),

    LUCIRA("LUCIRA"),

    MOCAMEDES("MOCÂMEDES"),

    BAIA_DOS_TIGRES("BAIA DOS TIGRES"),

    IONA("IONA"),

    TOMBWA("TÔMBWA"),

    CAINDE("CAINDE"),

    VIREI("VIREI"),

    BENGO("BENGO"),

    CAIONGO("CAIONGO"),

    CANGOLA("CANGOLA"),

    NOVA_AMBUILA("NOVA AMBUILA"),

    QUIPEDRO("QUIPEDRO"),

    BEMBE("BEMBE"),

    LUCUNGA("LUCUNGA"),

    MABAIA("MABAIA"),

    BUENGA_SUL("BUENGA SUL (QUIMBIANDA)"),

    CUILO_CAMBOSO("CUILO CAMBOSO"),

    NOVA_ESPERANCA("NOVA ESPERANÇA"),

    BUNGO("BUNGO"),

    CAMATAMBO("CAMATAMBO"),

    DAMBA("DAMBA"),

    LEMBOA("LÊMBOA"),

    NSOSSO("NSOSSO"),

    PETECUSSO("PETECUSSO"),

    ALDEIA_VICOSA("ALDEIA VIÇOSA"),

    CAMBAMBA("CAMBAMBA"),

    QUITEXE("QUITEXE"),

    VISTA_ALEGRE("VISTA ALEGRE"),

    BEU("BEU"),

    CUILO_FUTA("CUILO-FUTA"),

    MAQUELA_DO_ZOMBO("MAQUELA DO ZOMBO"),

    QUIBOCOLO("QUIBOCOLO"),

    SACANDICA("SACANDICA"),

    MACOCOLA("MACOCOLA"),

    MACOLO("MACOLO"),

    MASSAU("MASSAU"),

    MILUNGA("MILUNGA"),

    MUCABA("MUCABA (QUINZALA)"),

    UANDO_MUCABA("UANDO MUCABA"),

    DIMUCA("DIMUCA (ENTRE-OS-RIOS)"),

    NEGAGE("NEGAGE"),

    QUISSEQUE("QUISSEQUE"),

    ALFANDEGA("ALFÂNDEGA"),

    CUILO_POMBO("CUILO POMBO"),

    SANZA_POMBO("SANZA POMBO"),

    UAMBA("UAMBA"),

    PURI("PURI"),

    ALTO_ZAZA("ALTO ZAZA (FRONTEIRA)"),

    ICOCA("ICOCA"),

    QUIMBELE("QUIMBELE"),

    QUIVUENGA("QUIVUENGA (ZENGUELE)"),

    SONGO("SONGO"),

    UIGE("UÍGE"),

    BUELA("BUELA"),

    CUIMBA("CUIMBA"),

    LUVACA("LUVACA"),

    SERRA_DA_CANDA("SERRA DA CANDA"),

    QUIENDE("QUIENDE"),

    CALAMBATA("CALAMBATA"),

    CALUCA("CALUCA (CUMBI)"),

    LUVO("LUVO"),

    MADIMBA("MADIMBA"),

    MBANZA_KONGO("MBANZA KONGO"),

    LUFICO("LUFICO"),

    MPALA("MPALA (LULENDO)"),

    NOQUI("NOQUI"),

    MUSSERRA("MUSSERRA"),

    NZETO("NZETO"),

    QUIBALA_NORTE("QUIBALA NORTE (LOJE)"),

    QUINDEJE("QUINDEJE"),

    MANGUE_GRANDE("MANGUE GRANDE"),

    PEDRA_DE_FEITICO("PEDRA DE FEITIÇO"),

    QUELO("QUÊLO"),

    SOYO("SOYO"),

    SUMBA("SUMBA"),

    QUINSIMBA("QUINSIMBA"),

    QUINZAU("QUINZAU"),

    TOMBOCO("TOMBOCO");

    @Getter
    @Setter
    private String description;

    Comunas(String description) {
        this.description = description;
    }
}
